# Generated by Django 5.2.1 on 2025-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUnchained', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superheroes',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
